# SPDX-FileCopyrightText: 2026 The Botanu Authors
# SPDX-License-Identifier: Apache-2.0
#
# Repolinter configuration for LF AI & Data Foundation compliance.
# See: https://github.com/todogroup/repolinter

version: 2
axioms:
  linguist: language
  licensee: license
  packagers: packager

rules:
  # ---- License ----
  license-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - LICENSE*
          - COPYING*

  # ---- README ----
  readme-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - README*

  # ---- CONTRIBUTING ----
  contributing-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - CONTRIBUTING*
          - .github/CONTRIBUTING*

  # ---- Code of Conduct ----
  code-of-conduct-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - CODE_OF_CONDUCT*
          - .github/CODE_OF_CONDUCT*

  # ---- SECURITY ----
  security-file-exists:
    level: warning
    rule:
      type: file-existence
      options:
        globsAny:
          - SECURITY*
          - .github/SECURITY*

  # ---- NOTICE / attribution ----
  notice-file-exists:
    level: warning
    rule:
      type: file-existence
      options:
        globsAny:
          - NOTICE*

  # ---- DCO ----
  dco-file-exists:
    level: warning
    rule:
      type: file-existence
      options:
        globsAny:
          - DCO*

  # ---- CHANGELOG ----
  changelog-file-exists:
    level: warning
    rule:
      type: file-existence
      options:
        globsAny:
          - CHANGELOG*
          - HISTORY*

  # ---- No binaries ----
  binaries-not-present:
    level: error
    rule:
      type: file-type-exclusion
      options:
        type:
          - "**/*.exe"
          - "**/*.dll"
          - "**/*.so"
          - "**/*.dylib"
          - "**/*.pyc"
          - "**/*.pyo"

  # ---- Source files have SPDX headers ----
  source-license-headers-exist:
    level: warning
    rule:
      type: file-contents
      options:
        globsAll:
          - "src/**/*.py"
        content: "SPDX-License-Identifier"
        fail-on-non-existent: false

  # ---- No test credentials ----
  test-directory-exists:
    level: warning
    rule:
      type: file-existence
      options:
        globsAny:
          - tests/*
          - test/*
