# SPDX-FileCopyrightText: 2026 The Botanu Authors
# SPDX-License-Identifier: Apache-2.0

name: Bug Report
description: Report a bug in the Botanu SDK
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please fill in the details below to help us reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: Botanu SDK version
      description: "Output of `python -c 'import botanu; print(botanu.__version__)'`"
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: "Output of `python --version`"
      placeholder: "3.12.1"
    validations:
      required: true

  - type: dropdown
    id: init-mode
    attributes:
      label: Initialization mode
      options:
        - Standalone (no existing TracerProvider)
        - Attach (OTEL-native vendor — Splunk, Honeycomb, etc.)
        - Alongside (proprietary agent — Datadog, New Relic, etc.)
        - Unknown / not sure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal code or steps to reproduce the issue.
      render: python
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include tracebacks if applicable.
      render: shell
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        - OS and platform
        - OTel SDK / instrumentation versions
        - Existing observability vendor (Datadog, Splunk, etc.)
        - Collector configuration
    validations:
      required: false
